version: 2

sources:
  - name: earthquake_data
    database: earthquake-475820
    schema: earthquake_data
    freshness:
      warn_after: {count: 1, period: day}
      error_after: {count: 2, period: day}
    tables:
      - name: usgs_events
        description: "Raw USGS earthquake feed loaded from Confluent -> BigQuery"
        columns:
          - name: id
            tests:
              - not_null

      - name: continent_bounds
        description: "SPARQL-extracted continent coordinate bounds table used to enrich earthquake events with continent labels"
        columns:
          - name: continentLabel
            description: "Name of the continent (Africa, Asia, Europe, South America)"
          - name: minLat
            description: "Minimum latitude of the continent"
          - name: maxLat
            description: "Maximum latitude of the continent"
          - name: minLon
            description: "Minimum longitude of the continent"
          - name: maxLon
            description: "Maximum longitude of the continent"

models:
  - name: stg_usgs_events
    description: "Cleaned and enriched USGS Earthquake event data from BigQuery source."
    columns:
      - name: id
        description: "Unique earthquake event identifier."
        tests:
          - not_null

      - name: event_time
        description: "Timestamp when the event occurred."
        tests:
          - not_null

      - name: mag
        description: "Magnitude of the earthquake."
        tests:
          - not_null

      - name: depth_km
        description: "Depth of the event in kilometers."
        tests:
          - not_null

      - name: lat
        description: "Latitude of the event."
        tests:
          - not_null

      - name: lon
        description: "Longitude of the event."
        tests:
          - not_null
      
      - name: region
        description: "Location of the event."
        tests:
          - not_null
      
      - name: mag_category
        description: "Magnitude category of the event."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["Minor", "Light", "Moderate", "Major"]
      
      - name: dep_category
        description: "Depth category of the event."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ["Shallow", "Intermediate", "Deep"]

      - name: is_tsunami
        description: "Boolean flag for tsunami warnings."
        tests:
          - accepted_values:
              arguments:
                values: ["TRUE", "FALSE"]
